### ISSUE TITLE
chromVAR.pairwise peakfile

### ISSUE THREAD

**Issue by Hofphi** [ATpoint/Rscripts#2]
Hey,

I really like the small script you wrote using chromVAR for pairwise comparison of bulk-ATAC samples from two different condition. I would like to to the same test to identify motifs associated with variability in chromatin accessibility between samples.

I assume the input peak file is a merge of the peak files between replicates and condition, so only one big file containing all peaks?

Would appreciate your help.

Cheers,
Philipp

**Comment by ATpoint** [comment]
Hey, sorry for the late reply, I simply missed the issue. Yes the peak file is one file that should cover all relevant peaks in either condition. The differential analysis is then based on this peak file. I moved the script (and did some clean-ups), now it is here: https://github.com/ATpoint/Code_Cellar/blob/master/ATAC-seq/chromVAR.R
